server:
  port: 8000

spring:
  application:
    name: im_service
  datasource:
    url: jdbc:mysql://127.0.0.1/im?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.fandf.im.service.*.model.entity
  global-config:
    db-config:
      id-type: auto